import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Kantumruy_Pro } from "next/font/google";
import  NavbarComponent  from "@/components/navigation/NavbarComponent";
import   { FooterComponent } from "@/components/navigation/FooterComponent";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy-pro",
});

export const metadata: Metadata = {
  title: {
    template: '%s | Hak-Store',
    default: 'Hak-store'
  },
  keywords: 'Hak-Store, Hak Store Cambodia,  online shopping Cambodia, ecommerce Cambodia, Cambodia online store, buy online Cambodia, shopping online Cambodia, products Cambodia, best online shop Cambodia, affordable products Cambodia',
  description: "Generated by create next app",
  openGraph:
  {
    title: 'Hak-Store',
    description: 'Hak-Store is a modern e-commerce platform designed to provide customers across Cambodia with a convenient, reliable, and seamless online shopping experience.',
    images: ['/Hak-Store.png']
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${kantumruy.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavbarComponent/>
        <main className="flex-1">{children}</main>
        <FooterComponent/>
      </body>
    </html>
  );
}